name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala dependencias
      - name: Instalar dependencias
        run: npm install

      # 4. Compila el proyecto
      - name: Compilar proyecto
        run: npm run build
